Repository w3c/data-shapes, pull requests merged in 2025-09, with the labels that each got.

#548 Make references to original SHACL consistent
  shacl12-core/index.html
  shacl12-overview/index.html
  shacl12-sparql/index.html
Labels: Editorial

#550 add ui doc skeleton
  shacl12-ui/index.html
Labels: UI

#564 Add myself (Ieben) as editor of SHACL UI
  shacl12-ui/index.html
Labels: UI

#549 Profiles of and Profiling with starts
  shacl12-profiling/index.html
Labels: Profiles
